--- Generated by ./build/convert.lua
--- DO NOT EDIT THIS FILE DIRECTLY

local palette = {
  ansi = {
    bright = {
      blue = '#3FC4DE',
      cyan = '#6BE4E6',
      green = '#3FDAA4',
      magenta = '#F075B5',
      red = '#EC6A88',
      yellow = '#FBC3A7',
    },
    normal = {
      blue = '#26BBD9',
      cyan = '#59E1E3',
      green = '#29D398',
      magenta = '#EE64AC',
      red = '#E95678',
      yellow = '#FAB795',
    },
  },
  syntax = {
    apricot = '#F09483',
    cranberry = '#E95678',
    gray = '#BBBBBB',
    lavender = '#B877DB',
    rosebud = '#FAB795',
    tacao = '#FAC29A',
    turquoise = '#25B0BC',
  },
  ui = {
    accent = '#2E303E',
    accentAlt = '#6C6F93',
    background = '#282a2d',
    backgroundAlt = '#151620',
    border = '#1A1C23',
    darkText = '#06060C',
    lightText = '#D5D8DA',
    modified = '#21BFC2',
    negative = '#F43E5C',
    positive = '#09F7A0',
    secondaryAccent = '#E9436D',
    secondaryAccentAlt = '#E95378',
    shadow = '#16161C',
    tertiaryAccent = '#FAB38E',
    warning = '#27D797',
  },
}

local theme = {
  active_line_number_fg = '#7F8184',
  bg = '#282a2d',
  class_variable = {
    fg = '#D65271',
  },
  code_block = {
    fg = '#DC897A',
  },
  codelens_fg = '#4A4D60',
  color_column_fg = '#3C3F4C',
  comment = {
    fg = '#545658',
    italic = true,
  },
  constant = {
    fg = '#DC897A',
  },
  cursor_bg = '#E95378',
  cursor_fg = '#282a2d',
  cursorline_bg = '#2A2C32',
  delimiter = {
    fg = '#727374',
  },
  diff_added_bg = '#253F39',
  diff_deleted_bg = '#4A2024',
  error = '#F43E5C',
  external_link = '#E9436D',
  fg = '#BBBBBB',
  field = {
    fg = '#D65271',
  },
  float_bg = '#151620',
  float_border = '#151620',
  func = {
    fg = '#25A3AE',
  },
  git_added_fg = '#27A377',
  git_deleted_fg = '#F43E5C',
  git_ignored_fg = '#5C5E61',
  git_modified_fg = '#FAB38E',
  git_untracked_fg = '#27D797',
  inactive_line_number_fg = '#393B3E',
  indent_guide_active_fg = '#2E303E',
  indent_guide_fg = '#2B2D36',
  keyword = {
    fg = '#AA6FCA',
  },
  link = {
    fg = '#E5A98B',
  },
  match_paren = '#4A4D60',
  operator = {
    fg = '#BBBBBB',
  },
  parameter = {
    italic = true,
  },
  pmenu_bg = '#151620',
  pmenu_item_sel_fg = '#E95378',
  pmenu_thumb_bg = '#2F3137',
  pmenu_thumb_fg = '#4A4D60',
  regex = {
    fg = '#DC897A',
  },
  sidebar_bg = '#282a2d',
  sidebar_fg = '#7F8184',
  sign_added_bg = '#12B97E',
  sign_deleted_bg = '#B7384E',
  sign_modified_bg = '#239295',
  special_keyword = {
    fg = '#AA6FCA',
  },
  statusline_active_fg = '#2E303E',
  statusline_bg = '#282a2d',
  statusline_fg = '#7F8184',
  storage = {
    fg = '#AA6FCA',
  },
  string = {
    fg = '#E5A98B',
  },
  structure = {
    fg = '#E5B38F',
  },
  tag = {
    fg = '#D65271',
    italic = true,
  },
  template_delimiter = {
    fg = '#AA6FCA',
  },
  term_cursor_bg = '#D5D8DA',
  term_cursor_fg = '#4A4D60',
  title = {
    fg = '#D65271',
  },
  type = {
    fg = '#E5B38F',
  },
  variable = {
    fg = '#D65271',
  },
  visual = '#3C3F4C',
  warning = '#27A377',
  winbar = '#151620',
  winseparator_fg = '#1A1C23',
}

return { theme = theme, palette = palette }
-- vim: set nomodifiable :
