--- Generated by ./build/convert.lua
--- DO NOT EDIT THIS FILE DIRECTLY

local palette = {
  ansi = {
    bright = {
      blue = '#3FC4DE',
      cyan = '#6BE4E6',
      green = '#3FDAA4',
      magenta = '#F075B5',
      red = '#EC6A88',
      yellow = '#FBC3A7',
    },
    normal = {
      blue = '#26BBD9',
      cyan = '#59E1E3',
      green = '#29D398',
      magenta = '#EE64AC',
      red = '#E95678',
      yellow = '#FAB795',
    },
  },
  syntax = {
    apricot = '#F09483',
    cranberry = '#E95678',
    gray = '#BBBBBB',
    lavender = '#B877DB',
    rosebud = '#FAB795',
    tacao = '#FAC29A',
    turquoise = '#25B0BC',
  },
  ui = {
    accent = '#2E303E',
    accentAlt = '#6C6F93',
    background = '#313244',
    backgroundAlt = '#151620',
    border = '#1A1C23',
    darkText = '#06060C',
    lightText = '#D5D8DA',
    modified = '#21BFC2',
    negative = '#F43E5C',
    positive = '#09F7A0',
    secondaryAccent = '#E9436D',
    secondaryAccentAlt = '#E95378',
    shadow = '#16161C',
    tertiaryAccent = '#FAB38E',
    warning = '#27D797',
  },
}

local theme = {
  active_line_number_fg = '#83858F',
  bg = '#313244',
  class_variable = {
    fg = '#D75273',
  },
  code_block = {
    fg = '#DD8A7D',
  },
  codelens_fg = '#4F516C',
  color_column_fg = '#43445C',
  comment = {
    fg = '#5A5B68',
    italic = true,
  },
  constant = {
    fg = '#DD8A7D',
  },
  cursor_bg = '#E95378',
  cursor_fg = '#313244',
  cursorline_bg = '#303142',
  delimiter = {
    fg = '#767780',
  },
  diff_added_bg = '#2D464D',
  diff_deleted_bg = '#4A2024',
  error = '#F43E5C',
  external_link = '#E9436D',
  fg = '#BBBBBB',
  field = {
    fg = '#D75273',
  },
  float_bg = '#151620',
  float_border = '#151620',
  func = {
    fg = '#26A3B0',
  },
  git_added_fg = '#2AA67E',
  git_deleted_fg = '#F43E5C',
  git_ignored_fg = '#626471',
  git_modified_fg = '#FAB38E',
  git_untracked_fg = '#27D797',
  inactive_line_number_fg = '#414353',
  indent_guide_active_fg = '#2E303E',
  indent_guide_fg = '#303141',
  keyword = {
    fg = '#AB70CC',
  },
  link = {
    fg = '#E6AA8D',
  },
  match_paren = '#4F516C',
  operator = {
    fg = '#BBBBBB',
  },
  parameter = {
    italic = true,
  },
  pmenu_bg = '#151620',
  pmenu_item_sel_fg = '#E95378',
  pmenu_thumb_bg = '#37384C',
  pmenu_thumb_fg = '#4F516C',
  regex = {
    fg = '#DD8A7D',
  },
  sidebar_bg = '#313244',
  sidebar_fg = '#83858F',
  sign_added_bg = '#15BC84',
  sign_deleted_bg = '#BA3A55',
  sign_modified_bg = '#26959C',
  special_keyword = {
    fg = '#AB70CC',
  },
  statusline_active_fg = '#2E303E',
  statusline_bg = '#313244',
  statusline_fg = '#83858F',
  storage = {
    fg = '#AB70CC',
  },
  string = {
    fg = '#E6AA8D',
  },
  structure = {
    fg = '#E6B491',
  },
  tag = {
    fg = '#D75273',
    italic = true,
  },
  template_delimiter = {
    fg = '#AB70CC',
  },
  term_cursor_bg = '#D5D8DA',
  term_cursor_fg = '#4F516C',
  title = {
    fg = '#D75273',
  },
  type = {
    fg = '#E6B491',
  },
  variable = {
    fg = '#D75273',
  },
  visual = '#43445C',
  warning = '#2AA67E',
  winbar = '#151620',
  winseparator_fg = '#1A1C23',
}

return { theme = theme, palette = palette }
-- vim: set nomodifiable :
