--- Generated by ./build/convert.lua
--- DO NOT EDIT THIS FILE DIRECTLY

local palette = {
  ansi = {
    bright = {
      blue = '#3FC4DE',
      cyan = '#6BE4E6',
      green = '#3FDAA4',
      magenta = '#F075B5',
      red = '#EC6A88',
      yellow = '#FBC3A7',
    },
    normal = {
      blue = '#26BBD9',
      cyan = '#59E1E3',
      green = '#29D398',
      magenta = '#EE64AC',
      red = '#E95678',
      yellow = '#FAB795',
    },
  },
  syntax = {
    apricot = '#F09483',
    cranberry = '#E95678',
    gray = '#BBBBBB',
    lavender = '#B877DB',
    rosebud = '#FAB795',
    tacao = '#FAC29A',
    turquoise = '#25B0BC',
  },
  ui = {
    accent = '#2E303E',
    accentAlt = '#6C6F93',
    background = '#1d1f27',
    backgroundAlt = '#22242e',
    border = '#22242e',
    darkText = '#06060C',
    lightText = '#D5D8DA',
    modified = '#21BFC2',
    negative = '#F43E5C',
    positive = '#09F7A0',
    secondaryAccent = '#E9436D',
    secondaryAccentAlt = '#E95378',
    shadow = '#16161C',
    tertiaryAccent = '#FAB38E',
    warning = '#27D797',
  },
}

local theme = {
  active_line_number_fg = '#797C81',
  bg = '#1d1f27',
  class_variable = {
    fg = '#D55170',
  },
  code_block = {
    fg = '#DB887A',
  },
  codelens_fg = '#45475D',
  color_column_fg = '#353747',
  comment = {
    fg = '#4C4E53',
    italic = true,
  },
  constant = {
    fg = '#DB887A',
  },
  cursor_bg = '#E95378',
  cursor_fg = '#1d1f27',
  cursorline_bg = '#22242E',
  delimiter = {
    fg = '#6C6D71',
  },
  diff_added_bg = '#1B3533',
  diff_deleted_bg = '#4A2024',
  error = '#F43E5C',
  external_link = '#E9436D',
  fg = '#BBBBBB',
  field = {
    fg = '#D55170',
  },
  float_bg = '#22242e',
  float_border = '#22242e',
  func = {
    fg = '#24A2AD',
  },
  git_added_fg = '#24A075',
  git_deleted_fg = '#F43E5C',
  git_ignored_fg = '#54575D',
  git_modified_fg = '#FAB38E',
  git_untracked_fg = '#27D797',
  inactive_line_number_fg = '#2F3239',
  indent_guide_active_fg = '#2E303E',
  indent_guide_fg = '#262833',
  keyword = {
    fg = '#A96EC9',
  },
  link = {
    fg = '#E4A88A',
  },
  match_paren = '#45475D',
  operator = {
    fg = '#BBBBBB',
  },
  parameter = {
    italic = true,
  },
  pmenu_bg = '#22242e',
  pmenu_item_sel_fg = '#E95378',
  pmenu_thumb_bg = '#252732',
  pmenu_thumb_fg = '#45475D',
  regex = {
    fg = '#DB887A',
  },
  sidebar_bg = '#1d1f27',
  sidebar_fg = '#797C81',
  sign_added_bg = '#0FB67C',
  sign_deleted_bg = '#B3354C',
  sign_modified_bg = '#208F93',
  special_keyword = {
    fg = '#A96EC9',
  },
  statusline_active_fg = '#2E303E',
  statusline_bg = '#1d1f27',
  statusline_fg = '#797C81',
  storage = {
    fg = '#A96EC9',
  },
  string = {
    fg = '#E4A88A',
  },
  structure = {
    fg = '#E4B28F',
  },
  tag = {
    fg = '#D55170',
    italic = true,
  },
  template_delimiter = {
    fg = '#A96EC9',
  },
  term_cursor_bg = '#D5D8DA',
  term_cursor_fg = '#45475D',
  title = {
    fg = '#D55170',
  },
  type = {
    fg = '#E4B28F',
  },
  variable = {
    fg = '#D55170',
  },
  visual = '#353747',
  warning = '#24A075',
  winbar = '#22242e',
  winseparator_fg = '#22242e',
}

return { theme = theme, palette = palette }
-- vim: set nomodifiable :
